name = "wacta-scoring"
compatibility_date = "2024-09-23"
pages_build_output_dir = "public"

[[d1_databases]]
binding = "DB"
database_name = "wacta-scoring"
database_id = "3c073d9f-e205-468d-bf92-d0815aaaa247"